import "@/styles/globals.css";
import { ReactNode } from "react";
import Providers from "@/lib/providers";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { AppProps } from "next/app";
import { getServerSession, Session } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <Providers session={session}>{children}</Providers>
        {/* {children} */}
      </body>
    </html>
  );
}
